### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Dcyx** [zhongbin1/bert_tokenization_for_java#1]
https://github.com/zhongbin1/bert_tokenization_for_java/blob/1a050ba758584b22377f82b807d1ad9417b003bc/WordpieceTokenizer.java#L31

            if len(chars) > self.max_input_chars_per_word:
                output_tokens.append(self.unk_token)
                continue

**Comment by zhongbin1** [comment]
@Dcyx 你好，这里并不是bug。在bert实现的wordpiece逻辑中，认为一个英文单词若长度大于某个阈值，则完全保留，不做切分。

**Comment by zhongbin1** [comment]
@Dcyx 确实，应该添加unk，谢谢指出。Thanks！
